image: docker:latest
 
# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

stages:
 - build
 - test
 - deploy
 
#=========
# Build
#========= 
build:
  stage: build
  script:
  - docker build -t myimage/gitlab -f Dockerfile.dev .
  
#=========
# Test
#=========
test:
  stage: test
  script:
  - docker run myimage/gitlab npm run test -- --coverage
stages:
 - test
 - build
 - deploy

#=========
# Deploy
#=========
delpoy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-523913544371"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  
