sudo: required
language: node_js
node_js:
  - "lts/*"
services:
  - docker

before_install: 
  - docker build -t myimage/trav -f Dockerfile.dev .

script: 
  - docker run myimage/trav npm run test -- --coverage
