image: docker:latest
 
# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  REPOSITORY_URL: CallYourMomsLeague.us-east-2.elasticbeanstalk.com 

services:
- docker:dind

before_script:
 - docker info
 - apk add --no-cache curl jq python py-pip
 - pip install awscli

stages:
 - build
 - test
 - deploy
 
#=========
# Build
#========= 
build:
  stage: build
  script:
  - docker build -t myimage/gitlab -f Dockerfile.dev .
  
#=========
# Test
#=========
test:
  stage: test
  script:
  - docker run myimage/gitlab npm run test -- --coverage

#=========
# Deploy
#=========
deploy:
  stage: deploy
  only:
    - master
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  tags:
    - docker



