sudo: required
services:
  - docker

before_install: 
  - docker build -t myimage/trav -f Dockerfile.dev .

script: 
  - docker run myimage/trav npm run test -- --coverage

delpoy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-523913544371"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
  secret_access_key: AWS_ACCESS_KEY
    secure: "$AWS_SECRET_KEY"  